### ISSUE TITLE
1부 1장 설계와 아키텍처란?

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#1]

**Comment by dev-wooyeon** [comment]
아키텍처: 저수준의 세부사항과는 분리된 고수준의 무언가를 가리킬 때 흔히 사용됨 설계: 저수준의 구조 또는 결정사항 등을 의미할 때

설계와 아키텍처가 하는 일을 살펴보면 이러한 구분은 무의미하다.
이러한 저수준의 세부사항과 고수준의 결정사항은 집의 전체 설계의 구성요소가 된다.
고수준에서 저수준으로 향하는 의사결정의 연속성만 있을 뿐

목표는?
소프트웨어 아키텍처의 목표는 필요한 시스템을 만들고 유지보수하는데 투입되는 인력을 최소화 하는데 있다.

사례 연구
실제 사례로 엔지니어링 직원 수는 증가하지만 생산성은 점점 늘지 않고 코드 라인당 비용이 굉장히 커진 사례
코드를 깔끔하게 유지하는 잘 알려진 수련법 중 하나 테스트 주도 개발(TDD)를 통해 적용하지 않은 날보다 적용한 날이 대략 10% 빠르게 작업이 완성됐다는 사례
엉망으로 만들면 깔끔하게 유지할 때보다 항상 더 느리다
빨리 가는 유일한 방법은 제대로 가는 것이다.

결론
소프트웨어 아키텍처를 심각하게 고려할 수 있으려면 좋은 소프트웨어 아키텍처가 무엇인지 이해해야 한다.

**Comment by nomoreFt** [comment]
# 01. 설계와 아키텍쳐란?

* 아키텍쳐 : 저수준의 세부사항과는 분리된 고수준의 무언가를 지칭
* 설계 : 저수준의 구조 또는 결정사항을 의미

-> 저수준의 세부사항 + 고수준의 구조가 합쳐져 소프트웨어 전체 설계가 만들어진다.

> 좋은 소프트웨어 설계의 목표는 필요한 시스템을 만들고 유지보수의 비용이 최소화되는 것에 있다.


## 좋지 않은 설계의 징조

* 직원 수가 늘어나는 것에 비해 제품의 변경이 어려워진다.
* 코드 라인당 비용만 극적으로 증가하였다.
* 새로운 기능을 추가하는 데 많은 시간이 소요된다.

개발자가 늘고 일은 열심히 하지만, 코드 라인별 유지보수 비용이 증가한다. 이는 코드에 대한 생산성은 떨어지고 기능 추가, 변경에 대해 어려워진다.
곧 시장에 기민하게 대응할 수 없어 전혀 `Soft` 하지 않다. <br>

좋은 설계와 TDD 등의 방법으로 코드를 깔끔하게 유지하면 생산성이 높아진다. <br>
`빨리 가는 유일한 방법은 제대로 가는 것이다.`
