### ISSUE TITLE
3부 11장 DIP: 의존성 역전 원칙

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#11]

**Comment by dev-wooyeon** [comment]
- 의존성 역전 원칙(DIP)에서 말하는 유연성이 극대화된 시스템이란 소스코드 의존성이 추상에 의존하며 구체에는 의존하지 않는 시스템이다.

**Comment by nomoreFt** [comment]
# 11. DIP: 의존성 역전 원칙

> 고수준 모듈은 저수준 모듈의 구현에 의존해서는 안 된다.<br>
> 저수준 모듈이 고수준 모듈에서 정의한 추상 타입에 의존해야 한다.<br>
> 즉, 자신보다 변하기 쉬운 것에 의존하지 마라  

불변성이 보장된 컴포넌트나 클래스는 예외적으로 그냥 의존하여도 상관없다. ex) String <br>
변동성이 큰 구체화된 컴포넌트나 클래스는 `Interface`나 `abstract class`에 의존해야 한다.<br>

### 안정된 추상화

Interface는 상대적으로 기능에 대한 명세기 때문에 구현체보다 변화에 안정되어있다.<br>
하물며 뛰어난 소프트웨어 설계자와 아키텍트는 Interface의 변동을 최소화 하여 구현체에 기능을 추가하려고 노력한다.<br>

> 안정된 소프트웨어 아키텍쳐란 변동성이 큰 구현체에 의존하는 일을 지양하고, 안정된 추상 인터페이스를 선호하는 아키텍처란 뜻이다.

1. 변동성이 큰 구체 클래스를 참조하지 말라 : 대신 추상 인터페이스를 참조하라.
2. 변동성이 큰 구체 클래스로부터 파생하지 말라 : 상속은 신중하게 사용되어야 한다.
3. 구체 함수를 오버라이드 하지 말라 : 구체 함수는 소스코드 의존성을 필요로 하므로, 의존성을 상속하게 된다.
   차라리 추상함수로 선언하고, 구현체들에서 각자의 용도에 맞게 구현하라.
4. 구체적이며 변동성이 크다면 절대로 그 이름을 언급하지 말라.



고수준 모듈인 Car는 겨울용 Tire, 여름용 Tire에 의존하지 않는다.<br>
Car는 Tire의 종류가 아닌 추상화된 Tire Interface에 의존한다.<br>
Tire의 종류는 Car에 주입되는 DI에 의해 결정된다.<br>
저수준인 개별 Tire의 구현체들이 고수준인 Tire Interface를 의존하여 의존성 역전 법칙이다.<br> 
결과적으로 불변하는 Tire를 의존하는 Car를 불필요한 변화로부터 지키는 방법이다.
