### ISSUE TITLE
1부 2장 두가지 가치에 대한 이야기

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#2]

**Comment by dev-wooyeon** [comment]
소프트웨어 시스템은 이해관계자에게 서로 다른 두가지 가치를 제공하는데 행위(behavior)와 구조(structure)가 바로 그것이며, 두 가지 가치를 모두 반드시 높게 유지해야 하는 책임을 진다.

행위
이해관계자들을 위해 기계가 수익을 창출하거나 비용을 절약하도록 만들기 위해서 많은 프로그래머가 이러한 활동이 자신이 해야 할 일의 전부라고 생각하지만 틀렸다.

아키텍처
아키텍처의 가치는 소프트웨어(software)라는 단어와 관련이 있다. '부드러운 - soft'과 '제품 - ware'의 합성으로 soft가 아키텍처의 가치와 관련이 있다.
기계의 행위를 쉽게 변경할 수 있도록인데 소프트웨어는 하드웨어와 달리 반드시 변경하기 쉬워야 한다.
소프트웨어 개발비용의 증가를 결정짓는 주된 요인은 변경사항의 범위와 형태의 차이에 있다.
새로운 요청사항이 발생할때마다 바로 이전의 변경사항으 적용하는 것보다 조금 더 힘들어지는데 시스템의 형태와 요구사항의 형태가 서로 맞지 않기 때문이다.
이 문제는 당연히 시스템 아키텍처다. 형태에 독립적이어야 하고 그럴수록 더 실용적이다.

더 높은 가치
동작은 하지 않지만 변경이 쉬운 프로그램을 내게 준다면 돌아가도록 만들 수 있고 변경사항이 발생하더라도 유지보수 할 수 있다.

아이젠하워 매트릭스
소프트웨어의 첫 번째 가치인 행위는 긴급하지만 매번 높은 중요도를 가지는 것은 아니다 소프트웨어의 두 번째 가치인 아키텍처는 중요하지만 즉각적인 긴급성을 필요로 하는경우는 절대 없다. 업무관리자는 보통 아키텍처의 중요성을 평가할 만한 능력을 겸비하지 못하기 때문에 개발자는 딜레마에 빠리고 소프트웨어 개발자를 고용하는 이유는 바로 이 딜레마를 해결하기 위해서다.

아키텍처를 위해 투쟁하라
소프트웨어 개발팀은 다른 이해관계자들과 동등하게 논쟁한다.

**Comment by nomoreFt** [comment]
# 02. 두 가지 가치에 대한 이야기

개발자는 소프트웨어에서 두가지 가치인 `행위`와 `구조`를 밸런스 있게 추구해야한다.

## 행위

* 프로그래머는 수익을 창출하거나 비용을 절약하도록 만들기 위해 고용된다.
* 이해관계자의 요구사항을 코드로 구현하고 버그를 수정하는 것이 프로그래머의 전부라고 생각하는 사람이 많다.
* 코드를 짜고 수정하는 `행위`는 중요하지만, `구조`를 고려하지 않으면 코드를 수정하는 것이 어려워진다.


## 구조       

* 소프트웨어는 `소프트` 하기 때문에 변경이 쉬워야한다.
* 변경이 쉬우려면 `구조`가 중요하다.
* 시스템 아키텍쳐는 시스템의 형태와 요구사항의 형태가 서로 맞지 않을 때 변경사항의 범위와 형태를 결정한다.

-> 소프트웨어의 좋은 구조의 가치를 높이면 변경이 쉬워지고, 변경이 쉬워지면 생산성이 높아진다. 기능의 동작과 더불어 중요하게 생각해야하는 가치이다.


## 아이젠하워 매트릭스

드와이트 D. 아이젠하워 미국 대통령이 고안한 업무 우선순위 매트릭스이다. <br>

> 내겐 두 가지 유형의 문제가 있습니다. 하나는 긴급하며, 다른 하나는 중요합니다.<br> 
> 긴급한 문제는 중요하지 않으며, 중요한 문제는 절대 긴급하지 않습니다.<br>
> 드와이트 D. 아이젠하워

1. 긴급하고 중요한
2. 긴급하지는 않지만 중요한
3. 긴급하지만 중요하지 않은
4. 긴급하지도 중요하지도 않은

업무에 있어서 중요한 두가지 가치로 우선순위를 매길 수 있다. <br>
기능적 요구사항인 `행위`의 가치는 긴급하고, 아키텍쳐인 `구조`의 가치는 중요하다. <br>
중요한 `구조`의 가치가 상위 2개에 해당한다. 아키텍쳐의 중요성은 이해관계자가 파악하기 어렵기 때문에, 개발자가 이 사실을 이해하고 이를 위해 투쟁해야한다. <br>
보통의 상황에서 3순위인 긴급한 개발상황에서 아키텍쳐의 중요성이 고려되지 않은 상황이 1순위로 오인하기 쉽다.<br>
그러나 `구조`의 중요성이 후순위가 되면 시스템 개발 비용이 더 많이 들고, 변경하기 어려워진다.
