### ISSUE TITLE
2부 3장 패러다임 개요

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#3]

**Comment by dev-wooyeon** [comment]
3장. 패러다임 개요
소프트웨어 아키텍처는 코드로부터 시작한다. 따라서 아키텍처에 대한 논의도 코드가 최초로 작성된 시점부터, 우리가 코드를 통해 배운 내용을 살펴보는데서 출발

구조적 프로그래밍
무분별한 점프(goto 문장)는 프로그램 구조에 해롭다는 사실을 제시해 if/then/else와 do/whild/until과 같이 더 익숙한 구조로 대체
구조적 프로그래밍은 제어 흐름의 직접적인 전환에 대해 규칙을 부과한다.

객체 지향 프로그래밍
알골(ALGOL)언어의 함수 호출 스택 프레임(stack frame)을 힙(heap)으로 옮기면 함수 호출이 반환된 이후에도 함수에서 선언된 지역 변수가 오랫동안 유지될 수 있음을 발견했고,
바로 이러한 함수가 클래스의 생성자가 되었고 지역 변수는 인스턴스 변수, 중첩함수는 메서드가 되었다.
객체 지향 프로그래밍은 제허 흐름의 간접적인 전환에 대해 규칙을 부과한다.

함수형 프로그래밍
어떤 수학적 문제를 해결하는 과정에서 람다(lambda) 계산법을 발명했는데 함수형 프로그래밍은 이러한 연구결과에 직접적인 영향을 받아 만들어졌음
존 매카시가 만든 LISP언어의 근간이 되는 개념이 바로 람다 계산법인데 기초가 되는 개념은 3장. 패러다임 개요
소프트웨어 아키텍처는 코드로부터 시작한다. 따라서 아키텍처에 대한 논의도 코드가 최초로 작성된 시점부터, 우리가 코드를 통해 배운 내용을 살펴보는데서 출발

구조적 프로그래밍
무분별한 점프(goto 문장)는 프로그램 구조에 해롭다는 사실을 제시해 if/then/else와 do/whild/until과 같이 더 익숙한 구조로 대체
구조적 프로그래밍은 제어 흐름의 직접적인 전환에 대해 규칙을 부과한다.

객체 지향 프로그래밍
알골(ALGOL)언어의 함수 호출 스택 프레임(stack frame)을 힙(heap)으로 옮기면 함수 호출이 반환된 이후에도 함수에서 선언된 지역 변수가 오랫동안 유지될 수 있음을 발견했고,
바로 이러한 함수가 클래스의 생성자가 되었고 지역 변수는 인스턴스 변수, 중첩함수는 메서드가 되었다.
객체 지향 프로그래밍은 제허 흐름의 간접적인 전환에 대해 규칙을 부과한다.

함수형 프로그래밍
어떤 수학적 문제를 해결하는 과정에서 람다(lambda) 계산법을 발명했는데 함수형 프로그래밍은 이러한 연구결과에 직접적인 영향을 받아 만들어졌음
존 매카시가 만든 LISP언어의 근간이 되는 개념이 바로 람다 계산법인데 기초가 되는 개념은 **불변성(immutability)**으로 심볼(symbol)의 값이 변경되지 않는 다는 개념이다. 할당문이 전혀 없다는 뜻이기도 하다.
함수형 프로그래밍은 할당문에 대해 규칙을 부과한다.

생각할 거리
패러다임은 무엇을 해야 할지를 말하기 보다는 무엇을 해서는 안되는 지를 말해준다.으로 심볼(symbol)의 값이 변경되지 않는 다는 개념이다. 할당문이 전혀 없다는 뜻이기도 하다.
함수형 프로그래밍은 할당문에 대해 규칙을 부과한다.

생각할 거리
패러다임은 무엇을 해야 할지를 말하기 보다는 무엇을 해서는 안되는 지를 말해준다.

**Comment by nomoreFt** [comment]
# 03. 패러다임 개요

패러다임에는 3가지 종류가 있다.

`구조적 프로그래밍`, `객체 지향 프로그래밍`, `함수형 프로그래밍`

* 구조적 프로그래밍
    * 제어 흐름의 직접적인 전환에 대해 규칙을 부과한다.
  
`다익스트라`가 `goto`문의 해로움을 발견하고, `if/then/else`와 `do/while`과 같은 구조로 대체하면서 탄생했다.

* 객체 지향 프로그래밍
    * 제어 흐름의 간접적인 전환에 대해 규칙을 부과한다.

클래스, 인스턴스, 메서드와 함께 다형성이 등장하면서 탄생했다.

* 함수형 프로그래밍
    * 할당문에 대해 규칙을 부과한다.

`람다 계산법`을 기반으로 탄생했다. 불변성을 지키면서 프로그래밍을 하게 된다.


---

패러다임은 특정 행동들에 대한 제약, 규칙을 부과한다.<br>
이 세 가지 패러다임이 아키텍쳐의 세 가지 큰 관심사`(함수, 컴포넌트 분리, 데이터 관리)`와 어떻게 연관되는지 파악해야 한다.
