### ISSUE TITLE
2부 4장 구조적 프로그래밍

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#4]

**Comment by dev-wooyeon** [comment]
증명
데이크스트라가 초기에 인식한 문제는 모든 프로그램은 설령 단순할지라도 인간의 두뇌로 감당하기에는 너무 많은 세부사항을 담고 있었다.
데이크스트라는 연구를 진행하면서 goto 문장이 모듈을 더 작은 단위로 재귀적으로 분해하는 과정에 방해가 되는 경우가 있다는 사실을 발견했다.
대신 if/then/else 와 do/whild과 같은 분기와 반복이라는 단순한 제어구조에 해당한다는 사실을 발견했다.
이러한 제어 구조는 순차 실행(sequential execution)과 결합했을 때 특별하다는 사실을 깨달았다.
뵘과 야코피니가 데이크스트라보다 2년 앞서 발견했는데 모든 프로그램을 순차, 분기, 반복이라는 세 가지 구조만으로 표현할 수 있다는 사실을 증명했다.
즉, 모듈을 증명가능하게 하는 바로 그 제어 구조가 모든 프로그램을 만들 수 있는 제어구조의 최소 집합과 동일하다는 사실이었고, 구조적 프로그램이은 이렇게 탄생했다.
기능적 분해
모듈을 고수준의 기능들로 분해하고 저수준의 함수들로 분해할 수 있다.

테스트
구조적 프로그래밍은 프로그램을 증명 가능한 세부 기능 집합으로 재귀적으로 분해할 것을 강요한다. 그리고나서 테스트를 통해 증명 가능한 세부 기능들이 거짓인지를 증명하려고 시도한다.

이처럼 거짓임을 증명하려는 테스트가 실패한다면, 이 기능들은 목표에 부합할 만큼은 충분히 참이라고 여기게 된다.

결론
프로그래밍에서 모듈, 컴포넌트, 서비스가 쉽게 반증 가능한 단위를 만들어 낼 수 있는 바로 이 능력 때문

**Comment by nomoreFt** [comment]
# 04. 구조적 프로그래밍

`goto` 문에서 원자적으로 순차, 분기, 반복인 `if/then/else`와 `do/while/until/for`과 같은 구조로 대체하면서 탄생했다.<br>
이를 통해 아무리 거대한 요구사항이라도 고수준의 기능으로 분해할 수 있게 되었다.<br>
또한 고수준의 기능도 세부적인 저수준의 구현체들로 분해할 수 있게 되었다.<br>
이렇게 분해된 기능들은 증명 가능한 단위가 되고, 이를 통해 테스트를 통해 기능들이 거짓인지를 증명할 수 있게 되었다.<br>

흥미로운 점은 프로그래밍이 수학적 접근이 아닌 과학적 접근이라는 것이다.<br>
TDD는 증명 가능한 단위로 코드를 분해하고, 테스트를 통해 기능들이 거짓인지를 증명하는 것이다.<br>
우리는 프로그램이 완벽한 환경에서 항상 돌아가는것이 아닌, 테스트를 통해 증명한 범위안에서 돌아가는 것을 보장한다.<br>

* 구조적 프로그램이 제공하는 가치
    * 프로그램을 증명 가능한 단위로 분해할 수 있다.
    * 테스트를 통해 증명 가능한 단위가 거짓인지를 증명할 수 있다.
