### ISSUE TITLE
2부 5장 객체 지향 프로그래밍

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#5]

**Comment by dev-wooyeon** [comment]
- 캡슐화(encapsulation)
- 상속(inheritance)
- 다형성(polymorphism)

**Comment by nomoreFt** [comment]
# 05. 객체지향 프로그래밍

`캡슐화`, `상속`, `다형성`을 통해 객체를 만들고, 객체들을 조합하여 프로그램을 만드는 것이다.<br>


### 캡슐화

객체의 내부 변수는 감추고 일부 허용된 메서드만 외부에 노출시킨다.<br>

```java
public class Person {
    private String name;
    private int age;
     
    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }
     
    public String getName() {
        return name;
    }
     
    public int getAge() {
        return age;
    }
}
```

위의 코드에서 `name`과 `age`는 외부에서 접근할 수 없다.<br>
`getName()`과 `getAge()`를 통해서만 접근할 수 있다.<br>
사용자들은 Person 객체가 주는 Public 메서드인 `기능` 만으로 객체를 사용할 수 있다.<br>
즉, Person 내부 구현을 자유롭게 변경해도 외부에서 Person을 사용한 코드는 변경에 영향을 받지 않는다.<br>


### 상속

상속은 단순히 어떤 변수와 함수를 하나의 유효 범위로 묶어서 재정의하는 일에 불과하다.

### 다형성

함수를 가리키는 포인터를 응용한 것이 다형성이다.<br>
OO언어는 좀 더 안전하고 편리하게 사용할 수 있게 해주는데 포인터를 직접 사용하는 관례를 없애주며 실수할 위험이 없다.<br>


* 다형성이 가진 힘
  * 기존 구현의 변경 없이 새로운 기능을 추가할 수 있다.
  * 플러그인 스타일로 고수준 객체에서 저수준 객체를 분리할 수 있다.
  * 기존 코드 자체에서는 이미 고수준 객체로 `동작` 에 초점을 맞춰 구현했기 때문에, 저수준 객체를 변경해주면 기존코드 수정 없이 기능 변경이 가능하다.

* 어떻게 고수준에서 저수준을 분리하여 기능만 명명해 사용이 가능하게 됐을까? -> `의존성 역전`

기존에 저수준 객체를 사용하기 위해서는 고수준 객체가 저수준 객체를 직접 참조해야 했다.<br>
제어 흐름은 위에서 아래로 고정되어있을 수 밖에 없었다. ex)Java의 import, C언어의 include 등<br>
그러나 `Interface`가 등장하면서 고수준 모듈에서 기능을 선언하여 사용하고, 저수준 모듈에서 구현이 명명된 고수준 Interface를 참조하게 된다.<br>
이를 통해 제어 흐름이 역전되어 저수준 모듈이 고수준 모듈에 의존하게 된다.(방향이 반대)<br>

> 의존성 역전으로 각각의 컴포넌트가 서로 독립적으로 존재할 수 있게 된다. 일종의 객체 캡슐화랑 의도와 맥락이 비슷하다.<br>
> (UI, DB, APP등이 분리하여 독립적으로 존재할 수 있다.)

  
### 결론

객체지향 프로그래밍은 다형성을 이용하여 고수준의 기능을 저수준의 구현체로부터 분리할 수 있게 해준다.<br>
이를 통해 플러그인처럼 기능을 분리하여 저수준 모듈의 변경으로부터 자유로워진다.<br>
저수준의 세부사항은 플러그인 모듈로 제작할 수 있고, 고수준의 정책을 포함하는 모듈에 독립적으로 개발하고 배포할 수 있다.<br>
