### ISSUE TITLE
2부 6장 함수형 프로그래밍

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#6]

**Comment by dev-wooyeon** [comment]
- 불변성과 아키텍처
- 가변성의 분리
- 이벤트 소싱

**Comment by nomoreFt** [comment]
# 06. 함수형 

함수형 프로그래밍에서 핵심 논제는 `변수는 불변성을 가진다` 이다. 변수가 가변적이면 프로그램 설계시 많은 고려사항이 있다.
* 변수가 변할 가능성은 경합조건, 교착상태. 동시 업데이트 등 많은 문제를 야기한다.

그러나 우리는 모든 변수를 불변하게 유지할 수 없다. 그렇다면 어떻게 해야할까?

### 가변성의 분리

불변성과 관련하여 중요한 타협점은 가변 컴포넌트와 불변 컴포넌트로 분리하는 일이다.<br>
불변 컴포넌트에서는 함수형 방식으로 작업이 처리되며, 어떤 가변 변수도 사용되지 않는다.<br>
가변 컴포넌트에서는 객체지향 방식으로 작업이 처리되며, 불변 변수를 사용할 수 있다.<br>

> 현명한 아키텍트라면 가능한 많은 부분을 불변 컴포넌트로 분리하고, 가변 컴포넌트는 최소한으로 줄여야 한다.

### 이벤트 소싱

저장과 처리공간에 대한 제약이 사라지면서, 실 데이터를 Update, Delete하는 것이 아닌, Select, Insert만 하는 방식이 등장했다.<br>
이벤트 소싱은 상태가 아닌 트랜잭션을 저장하여 상태가 필요해지는 순간 초기 상태에서 모든 실행된 트랜잭션을 추적하여 현재 값을 파악한다.<br>

```
ex) 예를 들어 은행 계좌가 있다고 가정하자. 계좌에 입금, 출금, 이체 등의 트랜잭션이 발생한다.

이벤트 소싱은 계좌의 현재 잔액을 저장하는 것이 아닌, 계좌에 발생한 트랜잭션을 저장한다.

```

결과적으로 어플리케이션은 CRUD에서 CR만 수행한다.<br>
핵심은 이런 상태에서 모든 값들은 불변성을 가지게 된다.<br>

Event 트랜잭션을 저장하는 객체는 단순히 발생한 출금,입금 행위여서 불변성을 가지게 된다.<br>
추후에 필요할 때 상태를 계산한 후 저장하면 된다.<br>
데이터 저장소에서 변경과 삭제가 전혀 발생하지 않으므로 동시성, 경합조건, 교착상태 등의 문제가 발생하지 않는다.<br>
