### ISSUE TITLE
3부 8장 OCP: 개방 · 폐쇄 원칙

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#8]

**Comment by dev-wooyeon** [comment]
- 확장에는 열려있어야 하고, 변경에는 닫혀있어야 한다.
- 소프트웨어 아키텍처가 휼륭하다면 변경되는 코드의 양이 최소화

**Comment by nomoreFt** [comment]
# 08. OCP: 개방-폐쇄 원칙


> 소프트웨어 개체는 확장에는 열려 있어야 하고, 변경에는 닫혀 있어야 한다.

한마디로 변경하기 쉬워야 한다. 어떻게?<br>

기본적으로 다른 목적으로 변경이 발생하는 SRP를 지키는 게 설계한다.<br>
그리고 의존성 역전을 통해 변경에 대해 닫혀있게 만든다.<br>

* 확장에는 열려 있어야 한다.
  * Service에서 Repository를 사용한다. 이때 Repository를 구현한 클래스가 아닌 인터페이스를 사용한다.(의존성 역전)
  * Service에서는 해당 Interface를 사용해서 실제 Repository가 무엇인지 알 필요가 없다.
  * 저수준에서 Jpa던 Mybatis던 Service가 사용하고 있는 고수준 Repository Interface를 구현하여 의존해 사용한다.
  * Service는 원하는 기능을 메서드 수정을 해도 되고 따로 추가하여 Interface에 서술하기만 하면 된다.
* 변경에는 닫혀 있어야 한다. 
  * 특정 컴포넌트 변경에 대해 보호하려면 변경되는 컴포넌트가 보호하려는 컴포넌트를 의존해야 한다.
  * 구현체가 아무리 메서드 내용을 바꿔도 Return만 Interface에 맞춰주면 되기 때문에 Service는 구현체에 휘둘리지 않는다. 도구로써 사용할뿐!
  * ex) Service -> Repository(Interface)  <- (의존성 역전) JpaRepositoryImpl or MybatisRepositoryImpl


### 정보 은닉

의존성에 대한 방향을 제외하고 컴포넌트끼리의 정보 접근을 제한하기 위해 클래스를 사용하는 경우도 있다.<br>
클래스 A가 클래스 B에 의존하고, 클래스 B가 클래스 C에 의존할 때, 클래스 A는 직접적으로 클래스 C를 사용하지 않더라도 클래스 C에 의존하게 된다. 이를 `추이종속성`이라고 한다.<br>
컴포넌트별로 내부 참조를 많이 하지 않기 위해 변수의 제한을 두는 클래스이다.<br>



### 결론

시스템을 컴포넌트 단위로 분리하고, 저수준 컴포넌트에서 발생한 변경으로부터 고수준 컴포넌트를 보호할 수 있는 형태의 의존성 계층구조여야 한다.
