### ISSUE TITLE
3부 9장 LSP: 리스코프 치환 원칙

### ISSUE THREAD

**Issue by dev-wooyeon** [gro-w-up/clean-architecture#9]

**Comment by dev-wooyeon** [comment]
- LSP는 아키텍처 수준까지 확장할 수 있고, 반드시 확장해야만 한다. 치환가능성을 조금이라도 위배하면 시스템 아키텍처가 오염되어 상당량의 별도 메커니즘을 추가해야 할 수 있기 때문이다.
- 잘못된 객체를 상속하거나 올바르게 확장하지 못할 경우 위배 가능성이 크다.

**Comment by nomoreFt** [comment]
# 09. LSP: 리스코프 치환 원칙

> 상위 타입의 객체를 하위 타입의 객체로 치환해도 상위 타입을 사용하는 프로그램은 정상적으로 동작해야 한다.

상위 타입인 fruit이 있고 그 하위타입인 apple,grape 등등이 있다면, fruit의 자리에는 그 모든 하위타입이 들어가도 동일한 기능을 한다.<br>

```
public int eat(final Fruit fruit) {
    return fruit.getCalories();
}

Fruit 자리에 다른 과일인 하위타입이 들어와도 칼로리는 구해진다. 
```

초창기에는 `상속` 으로만 권장되어 왔는데 발전하면서 `추상체 Interface`또한 같은 원리가 적용되는 것으로 발전했다.<br>
고수준의 정의대로 저수준을 잘 구현해야 추후에 플러그인 식으로 교체 혹은 확장이 가능하고, 소스코드에 예외적인 if문들이 들어가지 않는다.<br>
간단한 치환 약속이 어겨지면 확장 하나에도 무수히 많은 예외들이 고려되어야 한다.<br>
LSP는 OCP를 만족시켜 변화에 더 유연하기 위한 제약이라고 생각이 된다.<br>
